spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crudrest
    username: crudrest
    password: crudrest
  flyway:
    baselineOnMigrate: true

logging:
  level:
    org:
      hibernate:
        type: trace















